let locatedata = {
    title:"Weather report",
    picinform:[
        {
            piclocate:"臺北市",
            picsrc:"homepagpic/travpic/TAIWAN/Taipei.jpg"
        },
        {
            piclocate:"新北市",
            picsrc:"homepagpic/travpic/TAIWAN/NewTaipei.jpg"
        },
        {
            piclocate:"基隆市",
            picsrc:"homepagpic/travpic/TAIWAN/Keelung.jpg"
        },
        {
            piclocate:"桃園市",
            picsrc:"homepagpic/travpic/TAIWAN/Taoyuan.jpg"
        },
        {
            piclocate:"新竹市",
            picsrc:"homepagpic/travpic/TAIWAN/Hsinchu.jpg"
        },
        {
            piclocate:"新竹縣",
            picsrc:"homepagpic/travpic/TAIWAN/HsinchuCounty.jpg"
        },
        {
            piclocate:"苗栗縣",
            picsrc:"homepagpic/travpic/TAIWAN/Miaoli.jpg"
        },
        {
            piclocate:"臺中市",
            picsrc:"homepagpic/travpic/TAIWAN/Taichung.jpg"
        },
        {
            piclocate:"彰化縣",
            picsrc:"homepagpic/travpic/TAIWAN/Changhua.jpg"
        },
        {
            piclocate:"南投縣",
            picsrc:"homepagpic/travpic/TAIWAN/Nantou.jpg"
        },
        {
            piclocate:"雲林縣",
            picsrc:"homepagpic/travpic/TAIWAN/Yunlin.jpg"
        },
        {
            piclocate:"嘉義市",
            picsrc:"homepagpic/travpic/TAIWAN/Chiayi.jpg"
        },
        {
            piclocate:"嘉義縣",
            picsrc:"homepagpic/travpic/TAIWAN/ChiayiCounty.jpg"
        },
        {
            piclocate:"臺南市",
            picsrc:"homepagpic/travpic/TAIWAN/Tainan.jpg"
        },
        {
            piclocate:"高雄市",
            picsrc:"homepagpic/travpic/TAIWAN/Kaohsiung.jpg"
        },
        {
            piclocate:"屏東縣",
            picsrc:"homepagpic/travpic/TAIWAN/Pingtung.jpg"
        },
        {
            piclocate:"宜蘭縣",
            picsrc:"homepagpic/travpic/TAIWAN/Yilan.jpg"
        },
        {
            piclocate:"花蓮縣",
            picsrc:"homepagpic/travpic/TAIWAN/hualian.jpg"
        },
        {
            piclocate:"臺東縣",
            picsrc:"homepagpic/travpic/TAIWAN/Taitung.jpg"
        },
        {
            piclocate:"澎湖縣",
            picsrc:"homepagpic/travpic/TAIWAN/Penghu.jpg"
        },
        {
            piclocate:"金門縣",
            picsrc:"homepagpic/travpic/TAIWAN/Kinmen.jpg"
        },
        {
            piclocate:"連江縣",
            picsrc:"homepagpic/travpic/TAIWAN/Lienchiang.jpg"
        },
    ]
}